- name: Maak een reverse lookup zone
  ansible.windows.win_powershell:
    script: |
      Add-DnsServerPrimaryZone -ComputerName "{{inventory_hostname}}" -DynamicUpdate "{{dynamic_update}}" -ReplicationScope "{{replication}}" -NetworkId "{{network_id}}" -ZoneFile "{{zone}}"

# - name: Kijkt of de zone present inventory_hostname


- name: Maak een pointer record
  community.windows.win_dns_record:
    name: idk
    type: PTR
    values: "{{inventory_hostname}}.{{dns_domain_name}}"
    state: present
    zone: "{{zone}}"