- hosts: LinuxServer
  gather_facts: true
  become: true
  roles:
  - { role: tasks/docker,        tag: [ 'docker']}

- hosts: routers 
  gather_facts: true
  become: true
  roles:
  - { role: tasks/x,        tag: [ 'x']}

- hosts: switches
  gather_facts: true
  become: true
  roles:
  - { role: tasks/x,        tag: [ 'x']}

- hosts: WindowsServer
  gather_facts: true
  become: true
  roles:
  - { role: tasks/x,        tag: [ 'x']}
