---
- hosts: WinS2019
  become: false
  gather_facts: false
  vars_files:
    - ../../group_vars/WindowsServer/vault.yml
    - ../../group_vars/WindowsServer/vars.yml

  tasks:
    - name: Include de AD users
      include_vars:
        file: ../../users/ad_users.yml
        name: ad_users

    - name: Creeër de AD users
      loop: "{{ ad_users.users }}"
      microsoft.ad.user:
        name: "{{ item.username }}"
        given_name: "{{ item.given_name }}"
        surname: "{{ item.surname }}"
        password: "{{ item.password }}"
        state: present
        attributes:
          displayName: "{{ item.given_name }} {{ item.surname }}"
