ansible_host: x.x.x.x

# ADDS
dns_domain_name: "noorderpoort.intern"
domain_netbios_name: "NOORDERPOORT"
check_netbios_name: "NOORDERPOORT\\Administrator"
domain_admin_user: "Administrator@noorderpoort.intern"

domain: "noorderpoort"
controller: "intern"

#OU
rootOU: "NPAfdelingen"

# DHCP
FQDN: "WinS2019.noorderpoort.intern"
start_range: 192.168.150.50
end_range: 192.168.150.200
subnet: 255.255.255.0

# DNS
dynamic_update: secure
replication: Forest
network_id: 192.168.150.0/24
zone: 150.168.192.in-addr.arpa  #het omgekeerde van je netwerk voorbeeld: 100.168.192.in-addr.arpa